name: Package-Debian-Build

on:
  push:
    tags:
      - '*'

  # allow manually starting this workflow
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major Version'
        required: true
        type: string
      minor_version:
        description: 'Minor Version'
        required: true
        type: string
      patch_version:
        description: 'Patch Version'
        required: true
        type: string

jobs:
  Debian:
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [jammy, noble]
    container:
      image: ghcr.io/tesseract-robotics/trajopt:${{ matrix.distro }}-${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: target_ws/src
          ref: ${{ github.event.inputs.major_version }}.${{ github.event.inputs.minor_version }}.${{ github.event.inputs.patch_version }}

      - name: Install Depends
        shell: bash
        run: |
          apt update
          apt upgrade -y
          apt install -y wget libompl-dev
      - name: Install Depends (non-noble)
        if: ${{ matrix.distro != 'noble' }}
        shell: bash
        run: |
          apt install -y software-properties-common
          add-apt-repository ppa:levi-armstrong/tesseract-robotics
          apt install -y taskflow
      - name: Install Depends (noble)
        if: ${{ matrix.distro  == 'noble' }}
        shell: bash
        run: |
          apt install -y libtaskflow-cpp-dev

      - name: Build and test
        uses: tesseract-robotics/colcon-action@v14
        with:
          before-script: source /opt/tesseract/install/setup.bash && source /opt/trajopt/install/setup.bash
          ccache-enabled: false
          vcs-file: dependencies.repos
          upstream-args: --cmake-args -DCMAKE_BUILD_TYPE=Release
          target-path: target_ws/src
          target-args: --cmake-args -DCMAKE_BUILD_TYPE=Release -DTESSERACT_PACKAGE=ON
          run-tests: false

      - name: Create artifacts directory
        run: |
          mkdir $GITHUB_WORKSPACE/artifacts

      - name: Package ruckig
        working-directory: upstream_ws/build/ruckig
        shell: bash
        run: |
          cpack --config CPackConfig.cmake
          cp ./*.deb $GITHUB_WORKSPACE/artifacts
          cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts

      - name: Package tesseract_planning
        working-directory: target_ws/build/tesseract_planning
        shell: bash
        run: |
          cpack --config CPackConfig.cmake
          cp ./*.deb $GITHUB_WORKSPACE/artifacts
          cp ./*.tar.xz $GITHUB_WORKSPACE/artifacts

      - uses: actions/upload-artifact@v7
        with:
          name: debian_package_${{ matrix.distro }}
          path: ${{ github.workspace }}/artifacts/*.deb

      - uses: actions/upload-artifact@v7
        with:
          name: archive_package_${{ matrix.distro }}
          path: ${{ github.workspace }}/artifacts/*.tar.xz
